# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions:     ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables', 'with_toc_data']

# Permalinks
permalink:        pretty

# Setup
title:            "Phil's Photos"
url:              http://philschatz.com

author:
  name:           'Philip Schatz'
  url:            https://github.com/philschatz
