# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            "Phil's Photos"
url:              http://philschatz.com

author:
  name:           'Philip Schatz'
  url:            https://github.com/philschatz
